rails/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Rails will create HTTP methods for all of the CRUD operations
  resources :articles

  # Defines the root path route ("/")
  root "welcome#index"
end

rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rails/app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
  def show
    # @article is an instance variable, and by default, Rails passes all instance variables to the view
    @article = Article.find(params[:id])
  end
  # Defines the POST action for /articles/new
  def new
    # Instantiates a new Article, but does not save it. This allows the page to be rendered, without validations like create.
    # Renders new.html.erb
    @article = Article.new
  end

  def create
    # By default, the parameters will be the fields of the form defined in articles/new.html.erb
    # Parameters: {"authenticity_token"=>"[FILTERED]", "article"=>{"title"=>"", "text"=>""}, "commit"=>"Save Article"}
    # render plain: params[:article].inspect

    # The class Article is defined in the model.
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  # Similar to new, where the article is fetched, but no changes are made.
  def edit
    @article = Article.find(params[:id])
  end

  # Refetches the article (if used after edit), runs validations and stores in DB
  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def article_params
    # require and permit are security features to limit the amount of parameters allowed to pass
    # http://weblog.rubyonrails.org/2012/3/21/strong-parameters/
    params.require(:article).permit(:title, :body)
  end
end

rails/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/helpers/articles_helper.rb
module ArticlesHelper
end

rails/app/helpers/welcome_helper.rb
module WelcomeHelper
end

rails/app/views/articles/_form.html.erb
<!-- This shared code between new and edit views is called a partial.
    Notice how we are not using an instance variable @article, the controller
    still manages the instance variable.
    -->
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

rails/app/views/articles/edit.hmtl.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

rails/app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.body %></td>
      <td><%= link_to 'See Full Article', article_path(article) %></td>
    </tr>
  <% end %>

  <%= link_to "New Article", new_article_path %>
</table>

rails/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>


<!--form_with is the helper to create a form. articles_path is a helper that looks at "articles" and dynamicaly
    determines the POST action for the controller which is ArticlesController in this case.
    HTML tag before updating model with validations:
      form_with scope: :article, url: articles_path, local: true do |form|
-->
<%#= form_with model: @article do |form| %>
<!--  <div>-->
<!--    <%#= form.label :title %><br>-->
    <%#= form.text_field :title %>
    <%# @article.errors.full_messages_for(:title).each do |message| %>
<!--    <div><%#= message %></div>-->
      <%# end %>
<!--  </div>-->
<!--  <div>-->
<!--    <%#= form.label :body %><br>-->
    <%#= form.text_field :body %>
    <%# @article.errors.full_messages_for(:body).each do |message| %>
<!--      <div><%#= message %></div>-->
    <%# end %>
<!--  </div>-->

<!--  <p>-->
    <%#= form.submit %>
<!--  </p>-->
<%# end %>
<%#= link_to 'Back', welcome_index_path %>

rails/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<ul>
  <li><%= link_to 'Back', articles_path %></li>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
</ul>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails/app/views/welcome/index.html.erb
<h1>Hello World!</h1>
<%= link_to 'My Blog', controller: 'articles' %>
<%= link_to 'Create New Article', new_article_path %>